### ISSUE TITLE
need some introductions

### ISSUE THREAD

**Issue by tht106** [RobRomijnders/dan#1]
Good job! By the way, I am being confused by 2 issues:

1) what does the "summary.txt" mean in the "print_mean_iou.py"? And I lacked it.

2) what does the "Problem definition json file" mean in the "utils_argarse.py"?

Traceback (most recent call last):
  File "./evaluate.py", line 92, in <module>
    main(sys.argv[1:])
  File "./evaluate.py", line 26, in main
    args = ssargs.parse_args(argv)
  File "F:\xunlei\dan-master\dan_for_uada\utils\utils_argparse.py", line 22, in parse_args
    open(self.args.training_problem_def_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'F:/xunlei/AdaptSegNet-master/data/problem_uda.json'
Traceback (most recent call last):
  File "./evaluate.py", line 92, in <module>
    main(sys.argv[1:])
  File "./evaluate.py", line 26, in main
    args = ssargs.parse_args(argv)
  File "F:\xunlei\dan-master\dan_for_uada\utils\utils_argparse.py", line 22, in parse_args
    open(self.args.training_problem_def_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'F:/xunlei/AdaptSegNet-master/data/problem_uda.json'
Traceback (most recent call last):
  File "./evaluate.py", line 92, in <module>
    main(sys.argv[1:])
  File "./evaluate.py", line 26, in main
    args = ssargs.parse_args(argv)
  File "F:\xunlei\dan-master\dan_for_uada\utils\utils_argparse.py", line 22, in parse_args
    open(self.args.training_problem_def_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'F:/xunlei/AdaptSegNet-master/data/problem_uda_vistas1.json'
Traceback (most recent call last):
  File "./evaluate.py", line 92, in <module>
    main(sys.argv[1:])
  File "./evaluate.py", line 26, in main
    args = ssargs.parse_args(argv)
  File "F:\xunlei\dan-master\dan_for_uada\utils\utils_argparse.py", line 22, in parse_args
    open(self.args.training_problem_def_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'F:/xunlei/AdaptSegNet-master/data/problem_uda_apollo.json'
Traceback (most recent call last):
  File "./scripts/print_mean_iou.py", line 56, in <module>
    main(direc=args.direc)
  File "./scripts/print_mean_iou.py", line 10, in main
    with open(join(direc, 'summary.txt'), 'w') as f_summ:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Program Files/Git/hdd/dropbox/Dropbox/grad/results/conf_matrices/results_from_0509_apollo/summary.txt'

THX!

**Comment by RobRomijnders** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Program
Files/Git/hdd/dropbox/Dropbox/grad/results/conf_matrices/results_from_0509_apollo/summary.txt'

We write all performances to that file. The file will be written, but you
must make sure all the folders actually exist.

Did you run the "set_env_names
<https://github.com/RobRomijnders/dan/blob/master/dan_for_uada/scripts/set_env_names.sh>.sh"
in the same console as where you are running the training? I would
recommend you set the log_direc to somewhere on your own pc


In the problem definitions we store all information related to that
specific training. and how the model outputs relate to the classes in the
data set. I put some examples in the attachment


Let me know if I can help in any other way

**Comment by tht106** [comment]
Thank you ! I figured it out.  
One more thing, can you share the problem-definition-json files such as:  "problem_uda.json", "problem_uda_vistas1", "problem_uda_apollo.json", "problem_uda_bdd.json". 
Thanks a lot!

**Comment by RobRomijnders** [comment]
Sure. I pushed them to `doc/problem_definitions` [link](https://github.com/RobRomijnders/dan/tree/master/doc/problem_definitions)
